apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-maven
  namespace: mavenapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: mymaven
          image: houcemdevops/maven-argo:24
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
